# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               David Hollenberger
tagline:             'A blog'
description:         ''
url:                 http://davidhollenberger.github.io
baseurl:             ''
paginate:            1

# About/contact
author:
  name:              David Hollenberger
  url:               https://twitter.com/dhollenberger
  email:             davejh@gmail.com

# Custom vars
version:             1.0.0

markdown: redcarpet
highlighter: pygments
